# -----------------------------------------------------------------------------
# Core Site Information
# -----------------------------------------------------------------------------

title: PIFSC Data Archiving Guide
description: A guide to data archiving and best practices at NOAA PIFSC.
url: "https://brighton-hedger-noaa.github.io"
baseurl: "/data-archiving-guide"

# The GitHub repository for your site
repository: brighton-hedger-noaa/data-archiving-guide

# Set a path to your logo
# logo: "/assets/images/your-logo.png"

# -----------------------------------------------------------------------------
# Navigation & Search
# -----------------------------------------------------------------------------

# Enable the site search
search_enabled: true

# Enable the navigation sidebar
nav_enabled: true

# Links that appear in the top right corner
aux_links:
  "View on GitHub":
    - "https://github.com/brighton-hedger-noaa/data-archiving-guide"

# -----------------------------------------------------------------------------
# Page Features
# -----------------------------------------------------------------------------

# Enable the copy button on code blocks
enable_copy_code_button: true

# Enable Mermaid diagrams for flowcharts
mermaid:
  version: "9.1.6"

# Enable heading anchor links
heading_anchors: true

# -----------------------------------------------------------------------------
# Footer Content
# -----------------------------------------------------------------------------



# Custom footer text
footer_content: "Questions? Reach out to the Data Services Team!"

# "Back to top" link
back_to_top: false


# Show "Edit this page on GitHub" link in the footer
#gh_edit_link: true
#gh_edit_link_text: "Edit this page on GitHub"
#gh_edit_repository: "https://github.com/brighton-hedger-noaa/data-archiving-guide"
#gh_edit_branch: "main"
#gh_edit_view_mode: "tree"

# -----------------------------------------------------------------------------
# Color Scheme & Callouts
# -----------------------------------------------------------------------------

# The custom color scheme we created
color_scheme: pifsc

# You can customize the default titles and colors of callouts (e.g., Note, Warning)
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue

# -----------------------------------------------------------------------------
# Build Settings
# -----------------------------------------------------------------------------

# The theme we are using
theme: just-the-docs

# List of plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Files to exclude from the build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

just_the_docs:
  custom_css:
    - /assets/css/custom.css

sass:
  style: compressed
